name: ALO-001 CI

on:
  push:
    branches:
      - 'alo-001/**'
      - 'copilot/alo-001-google-oauth'
  pull_request:
    branches:
      - main

jobs:
  build-and-verify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Verify .env.example exists
        run: |
          if [ ! -f .env.example ]; then
            echo "Error: .env.example file not found"
            exit 1
          fi
          echo "✓ .env.example file found"
          cat .env.example
      
      - name: Verify required environment variables in .env.example
        run: |
          required_vars=("GOOGLE_CLIENT_ID" "SEEDBRINGER_ALLOWLIST" "COUNCIL_ALLOWLIST")
          for var in "${required_vars[@]}"; do
            if ! grep -q "^$var=" .env.example; then
              echo "Error: $var not found in .env.example"
              exit 1
            fi
            echo "✓ $var found in .env.example"
          done
      
      - name: Build TypeScript
        run: npm run build
      
      - name: Verify build output
        run: |
          if [ ! -d dist ]; then
            echo "Error: dist directory not created"
            exit 1
          fi
          if [ ! -f dist/server.js ]; then
            echo "Error: dist/server.js not found"
            exit 1
          fi
          echo "✓ TypeScript build successful"
          ls -la dist/
      
      - name: Run tests
        run: npm test
